#!/usr/bin/env bash
# Displays the time for 12hrs and 59mins.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
